version: 0.0
os: linux

files:
  - source: board-server/build/libs/board-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/app/
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu